config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('student/', include('student.urls', namespace='student')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Digi Academy Admin'
admin.site.site_title = 'Digi Academy Admin'
admin.site.index_title = 'Digi Academy Admin'

student/urls.py
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path('', views.StudentDashboard.as_view(), name='student-dashboard'),
    path('explore/', views.CourseList.as_view(), name='student-explore'),
    path('subscribe/', views.course_subscribe, name='subscribe'),
    path('my-courses/', views.SubscribedCourses.as_view(), name='my-courses'),
    path('unsubscribe/', views.unsubscribe, name='un-subscribe'),
    path('search/', views.SearchCourse.as_view(), name='search'),
]

teacher/urls.py
from django.urls import path

from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.TeacherDashboard.as_view(), name='teachers-dashboard'),
    path('courses/', views.CoursesList.as_view(), name='teachers-courses'),
    path('add-courses/', views.CourseCreate.as_view(), name='create-courses'),
    path('<int:pk>/delete/', views.delete_content, name='delete-content'),
    path('<int:pk>/delete/courses/', views.delete_course, name='delete-course'),
    path('<int:pk>/edit/', views.edit_content, name='edit-content'),
    path('<int:pk>/add-topic/', views.add_topic, name='add_topic'),
    path('student-list/', views.StudentList.as_view(), name='student-list'),
    path('confirm-order/<int:pk>/', views.confirm_order, name='confirm-order'),
    path('process-payment/', views.process_payment, name='process_payment'),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.welcome_page, name='welcome'),
    path('student-login/', views.StudentLoginView.as_view(), name='student-login'),
    path('student-register/', views.StudentRegisterView.as_view(), name='student-register'),
    path('verify-otp/<email>', views.VerifyOtp.as_view(), name='verify-otp'),
    path('teacher-login/', views.TeacherLoginView.as_view(), name='teacher-login'),
    path('teacher-register/', views.TeacherRegisterView.as_view(), name='teacher-register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

student/models.py
from django.conf import settings
from django.db import models
from teacher.models import Course

User = settings.AUTH_USER_MODEL


class CourseRegistration(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    registration_date = models.DateField(auto_now_add=True)
    subscribed = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = 'Course Registrations'

    def __str__(self):
        return f"{self.course.course_name}"

teacher/models.py
from django.conf import settings
from django.db import models

User = settings.AUTH_USER_MODEL


class Course(models.Model):
    instructor = models.ForeignKey(User, on_delete=models.CASCADE)
    course_name = models.CharField(max_length=100, null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    published_date = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)

    class Meta:
        verbose_name_plural = "Courses"
        ordering = ['-published_date']

    def __str__(self):
        return self.course_name


class Content(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    topic = models.CharField(max_length=100, null=True, blank=True)
    content = models.TextField(null=True, blank=True)

student/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views import View
from django.core import serializers
from django.views.generic import TemplateView, ListView
from teacher.models import Course
from .models import CourseRegistration

User = get_user_model()


class StudentDashboard(TemplateView):
    template_name = 'student/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"DA | {self.request.user}"
        context['navbar'] = "student-dashboard"
        context['user'] = User.objects.get(id=self.request.user.id)
        return context


class CourseList(ListView):
    paginate_by = 8
    model = Course
    template_name = 'student/explore.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Courses | {self.request.user.first_name}"
        context['navbar'] = "student-explore"
        return context


def course_subscribe(request):
    c_id = request.GET.get('id')
    c = Course.objects.get(id=c_id)
    cr = CourseRegistration.objects.filter(student=request.user)
    data = {}
    if cr.filter(course_id=c_id).exists():
        data['message'] = "Already Subscribed to Course"
        data['color'] = "alert-danger"

    else:
        CourseRegistration.objects.create(
            student=request.user,
            course=c,
            subscribed=True
        )
        data['message'] = "Successfully Subscribed to course. Go to you Course Section"
        data['color'] = "alert-success"
    return JsonResponse(data)


class SubscribedCourses(ListView):
    template_name = 'student/my-courses.html'
    paginate_by = 8

    def get_queryset(self):
        return CourseRegistration.objects.filter(student=self.request.user, subscribed=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"My Courses | {self.request.user.first_name}"
        context['navbar'] = "student-courses"
        return context


def unsubscribe(request):
    if request.method == 'GET':
        idx = request.GET.get('idx')
        crd = CourseRegistration.objects.get(id=idx)
        crd.delete()
        return JsonResponse({"data": idx})


class SearchCourse(ListView):
    paginate_by = 8
    model = Course
    template_name = 'student/explore.html'

    def get_queryset(self):
        return Course.objects.filter(course_name__icontains=self.request.GET.get('query'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Courses | {self.request.user.first_name}"
        context['navbar'] = "student-explore"
        return context

teacher/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, ListView

from .models import Course, Content
from student.models import CourseRegistration
from paypal.standard.forms import PayPalPaymentsForm
import random

User = get_user_model()


class TeacherDashboard(TemplateView):
    template_name = 'teacher/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"DA | {self.request.user.first_name}"
        context['navbar'] = "teacher-dashboard"
        return context


class CoursesList(ListView):
    template_name = 'teacher/courses.html'
    model = Course

    def get_queryset(self):
        return Course.objects.filter(instructor=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"DA | {self.request.user.first_name}"
        context['navbar'] = "teacher-courses"
        return context


class CourseCreate(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'teacher/add-courses.html',
                      {'title': f'DA | {self.request.user.first_name}', 'navbar': 'teacher-courses'})

    def post(self, request, *args, **kwargs):
        course_title = request.POST.get('course-title')
        price = request.POST.get('price')
        try:
            c = Course.objects.create(
                instructor=request.user,
                course_name=course_title,
                price=price,
            ).save()
            messages.success(request, "Course created successfully")
            return redirect('teacher:teachers-courses')
        except Exception as e:
            messages.error(request, "Something went wrong. Try again")
            print(e)
            return redirect('teacher:create-courses')


def delete_content(request, pk):
    obj = Content.objects.get(id=pk)
    obj.delete()
    return redirect('teacher:teachers-courses')


def edit_content(request, pk):
    c = Content.objects.get(id=pk)
    if request.method == 'POST':
        cname = request.POST.get('course-title')
        desc = request.POST.get('course-description')
        content = request.POST.get('content')
        c.course.instructor = request.user
        c.course_name = cname
        c.topic = desc
        c.content = content
        c.save()
        messages.success(request, "Updated the Selected Course")
        return redirect('teacher:teachers-courses')
    context = {
        'course': c,
        'title': f'DA | {request.user.first_name}',
        'navbar': 'teacher-courses'
    }
    return render(request, 'teacher/edit-course.html', context)


class StudentList(ListView):
    template_name = 'teacher/students.html'
    paginate_by = 8

    def get_queryset(self):
        return CourseRegistration.objects.filter(course__instructor=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"DA | {self.request.user.first_name}"
        context['navbar'] = "teacher-students"
        return context


def add_topic(request, pk):
    if request.method == 'GET':
        course = Course.objects.get(id=pk)
        context = {
            'course': course,
            'title': f'DA | {request.user.first_name}',
            'navbar': 'teacher-courses'
        }
        return render(request, 'teacher/add-topics.html', context)
    else:
        course = Course.objects.get(id=pk)
        topic = request.POST.get('topic')
        content = request.POST.get('content')
        try:
            c = Content.objects.create(
                course=course,
                topic=topic,
                content=content,
            ).save()
            messages.success(request, "Topic added successfully")
            return redirect('teacher:teachers-courses')
        except Exception as e:
            messages.error(request, "Something went wrong. Try again")
            print(e)
            return redirect('teacher:teachers-courses')


def delete_course(request, pk):
    obj = Course.objects.get(id=pk)
    obj.delete()
    return redirect('teacher:teachers-courses')


def confirm_order(request, pk):
    course = Course.objects.get(id=pk)
    if request.method == 'POST':
        cr = CourseRegistration.objects.create(
            course=course,
            student=request.user,
        )
        request.session['registration'] = cr.id
        return redirect('teacher:process_payment')
    context = {
        'title': f'DA | {request.user}',
        'navbar': 'teacher-courses',
        'course': course,
    }
    return render(request, 'student/order-confirm.html', context)


def process_payment(request):
    cr_id = request.session.get('registration')
    cr = CourseRegistration.objects.get(id=cr_id)
    paypal_dict = {'business': settings.PAYPAL_RECEIVER_EMAIL,
                   'amount': str(cr.course.price),
                   'item_name': str(f'Order- {cr.course.course_name}'),
                   'invoice': str(cr.id),
                   'currency_code': 'USD',
                   'notify_url': f"http://{request.get_host()}{reverse('paypal-ipn')}",
                   'return_url': f"http://{request.get_host()}{reverse('teacher:payment_done')}",
                   'cancel_return': f"http://{request.get_host()}{reverse('teacher:payment_cancelled')}"}

    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {
        'title': f'DA | {request.user}',
        'navbar': 'teacher-courses',
        'form': form,
    }
    return render(request, 'student/pay.html', context)


@csrf_exempt
def payment_done(request):
    return render(request, 'student/payment-success.html')


@csrf_exempt
def payment_canceled(request):
    return render(request, 'student/payment-failed.html')

teacher/templates/teacher/add-courses.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
<div class="container" style="min-height: 100vh">
    {% include 'components/alert.html' %}
    <div class="row my-4 mx-1">
        <div class="card shadow-custom">
            <div class="card-title h2 text-center mt-1">
                Add New Course
                <hr class="mt-1 mb-0">
            </div>
            <div class="card-body">
                <form action="{% url 'teacher:create-courses' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="course-title" class="form-control mb-2" placeholder="Course Title">
                    <button type="submit" class="btn btn-block btn-dark mt-3">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block footbar %}
{% include 'components/footer.html' %}
{% endblock %}

teacher/templates/teacher/add-topics.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row my-4 mx-1">
            <div class="card shadow-custom">
                <div class="card-title h2 text-center mt-1">
                    Add New Course
                    <hr class="mt-1 mb-0">
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <input type="text" name="course-title" class="form-control mb-2" placeholder="Course Title"
                               value="{{ course.course_name }}" readonly>
                        <input type="text" name="topic" class="form-control mb-2"
                               placeholder="Topic">
                        <textarea class="form-control mb-2" name="content" placeholder="Write Your Content here"
                                  rows="8"></textarea>
                        <input type="submit" class="btn btn-block btn-dark mt-3" value="Submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}

teacher/templates/teacher/course-delete.html
<div class="modal top fade" id="course-delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
     data-mdb-backdrop="static" data-mdb-keyboard="true">
    <div class="modal-dialog modal-sm  modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center">
                Do you want to delete selected course
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-mdb-dismiss="modal">
                    Close
                </button>
                <a href="{% url 'teacher:delete-course' t.id %}" class="btn btn-sm btn-danger">delete</a>
            </div>
        </div>
    </div>
</div>

teacher/templates/teacher/course-detail.html
<div class="modal top fade" id="course-detail" tabindex="-1" aria-labelledby="topic-detail" aria-hidden="true"
     data-mdb-backdrop="static" data-mdb-keyboard="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="topic-name"></h5>
            </div>
            <hr class="mt-0 mb-0">
            <div class="modal-body" id="content">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-block btn-sm btn-dark" data-mdb-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>

teacher/templates/teacher/courses.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row my-4 mx-1">
            <a href="{% url 'teacher:create-courses' %}" class="btn btn-outline-success">Add New Course</a>
        </div>
        <div class="row my-4 mx-1">
            <div class="card shadow-custom">
                <div class="card-title text-center mt-2 h2">
                    Your Courses
                    <hr class="mt-1 mb-0">
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover table-sm table-light ">
                            <thead class="table-dark">
                            <tr class="text-center">
                                <th scope="col">#</th>
                                <th scope="col">Course</th>
                                <th scope="col">Topic</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for course in course_list %}
                                <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td>{{ course.course_name }}<br><a
                                            href="{% url 'teacher:add_topic' course.id %}">Add Topics</a><br>
                                        <a href="{% url 'teacher:delete-course' course.id %}" class="text-danger">Delete
                                            Course</a>
                                    </td>
                                    <td>
                                        {% for topic in course.content_set.all %}
                                            {{ forloop.counter }}.
                                            <a href="#" class="text-success me-5" id="detail"
                                               data-mdb-toggle="modal"
                                               data-mdb-target="#course-detail"
                                               data-title="{{ topic.topic }}"
                                               data-content="{{ topic.content }}">{{ topic.topic }}</a>
                                            <br>
                                            &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'teacher:edit-content' topic.id %}"
                                                                       class="text-danger">edit&nbsp;&nbsp;|&nbsp;&nbsp;</a>
                                            <a href="{% url 'teacher:delete-content' topic.id %}" class="text-danger">delete</a>
                                            <hr class="my-1">
                                        {% empty %}
                                            <p class="text-danger my-0">No topics yet</p>
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="7" class="text-center">No Courses Found</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                {% include 'teacher/course-detail.html' %}
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}
{% block app-js %}
    <script>
        $('[id="detail"]').on('click', function () {
            $('#topic-name').text($(this).data('title'));
            $('#content').text($(this).data('content'));
        });
    </script>
{% endblock %}

teacher/templates/teacher/edit-course.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row my-4 mx-1">
            <div class="card shadow-custom">
                <div class="card-title h2 text-center mt-1">
                    Add New Course
                    <hr class="mt-1 mb-0">
                </div>
                <div class="card-body">
                    <form action="{% url 'teacher:edit-content' course.id %}" method="POST">
                        {% csrf_token %}
                        <input type="text" name="course-title" class="form-control mb-2" placeholder="Course Title"
                               value="{{ course.course.course_name }}" readonly>
                        <input type="text" name="course-description" class="form-control mb-2"
                               placeholder="Course Description" value="{{ course.topic }}">
                        <textarea class="form-control mb-2" name="content" placeholder="Write Your Content here"
                                  rows="8">{{ course.content }}</textarea>
                        <button type="submit" class="btn btn-block btn-dark mt-3">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}

teacher/templates/teacher/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row d-flex justify-content-center align-items-center mt-4 mx-1" style="min-height: 60vh">
            <div class="card shadow-custom">
                <h4 class="text-center p-2">Welcome To Digi Academy
                </h4>
                <hr>
                <div class="row text-center mt-4 mb-4">
                    <div class="col-lg-3">
                        <a href="{% url 'teacher:teachers-dashboard' %}" class="btn btn-sm btn-success mb-2 w-100">Dashboard</a>
                    </div>
                    <div class="col-lg-3">
                        <a href="{% url 'teacher:teachers-courses' %}"
                           class="btn btn-sm btn-success mb-2 w-100">Courses</a>
                    </div>
                    <div class="col-lg-3">
                        <a href="{% url 'teacher:student-list' %}"
                           class="btn btn-sm btn-success mb-2 w-100">Students</a>
                    </div>
                    <div class="col-lg-3">
                        <a href="{% url 'user:logout' %}" class="btn btn-sm btn-danger mb-2 w-100">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}

teacher/templates/teacher/students.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row my-4 mx-1">
            <div class="card shadow-custom p-2">
                <h5 class="text-center">Student List</h5>
                <hr class="mt-0">
                <div class="table-responsive">
                    <table class="table table-sm table-striped table-hover table-light border-light">
                        <thead class="table-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Student</th>
                            <th scope="col">Course</th>
                            <th scope="col">Subscribed-On</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ object.student.first_name }}</td>
                                <td>{{ object.course.course_name}}</td>
                                <td>{{ object.registration_date }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4" class="text-center">No Data Found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if object_list %}
                    <div class='pagination justify-content-center pb-2' id="pg">
                        {% if page_obj.has_previous %}
                            <a href='?page={{ page_obj.previous_page_number }}'>Previous </a>
                        {% endif %}
                        <span class='mx-2'>
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                        {% if page_obj.has_next %}
                            <a href='?page={{ page_obj.next_page_number }}'>Next</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}