config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('student/', include('student.urls', namespace='student')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Digi Academy Admin'
admin.site.site_title = 'Digi Academy Admin'
admin.site.index_title = 'Digi Academy Admin'

student/urls.py
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path('', views.StudentDashboard.as_view(), name='student-dashboard'),
    path('explore/', views.CourseList.as_view(), name='student-explore'),
    path('subscribe/', views.course_subscribe, name='subscribe'),
    path('my-courses/', views.SubscribedCourses.as_view(), name='my-courses'),
    path('unsubscribe/', views.unsubscribe, name='un-subscribe'),
    path('search/', views.SearchCourse.as_view(), name='search'),
]

teacher/urls.py
from django.urls import path

from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.TeacherDashboard.as_view(), name='teachers-dashboard'),
    path('courses/', views.CoursesList.as_view(), name='teachers-courses'),
    path('add-courses/', views.CourseCreate.as_view(), name='create-courses'),
    path('<int:pk>/delete/', views.delete_content, name='delete-content'),
    path('<int:pk>/delete/courses/', views.delete_course, name='delete-course'),
    path('<int:pk>/edit/', views.edit_content, name='edit-content'),
    path('<int:pk>/add-topic/', views.add_topic, name='add_topic'),
    path('student-list/', views.StudentList.as_view(), name='student-list'),
    path('confirm-order/<int:pk>/', views.confirm_order, name='confirm-order'),
    path('process-payment/', views.process_payment, name='process_payment'),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.welcome_page, name='welcome'),
    path('student-login/', views.StudentLoginView.as_view(), name='student-login'),
    path('student-register/', views.StudentRegisterView.as_view(), name='student-register'),
    path('verify-otp/<email>', views.VerifyOtp.as_view(), name='verify-otp'),
    path('teacher-login/', views.TeacherLoginView.as_view(), name='teacher-login'),
    path('teacher-register/', views.TeacherRegisterView.as_view(), name='teacher-register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

student/models.py
from django.conf import settings
from django.db import models
from teacher.models import Course

User = settings.AUTH_USER_MODEL


class CourseRegistration(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    registration_date = models.DateField(auto_now_add=True)
    subscribed = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = 'Course Registrations'

    def __str__(self):
        return f"{self.course.course_name}"

teacher/models.py
from django.conf import settings
from django.db import models

User = settings.AUTH_USER_MODEL


class Course(models.Model):
    instructor = models.ForeignKey(User, on_delete=models.CASCADE)
    course_name = models.CharField(max_length=100, null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    published_date = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)

    class Meta:
        verbose_name_plural = "Courses"
        ordering = ['-published_date']

    def __str__(self):
        return self.course_name


class Content(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    topic = models.CharField(max_length=100, null=True, blank=True)
    content = models.TextField(null=True, blank=True)

student/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views import View
from django.core import serializers
from django.views.generic import TemplateView, ListView
from teacher.models import Course
from .models import CourseRegistration

User = get_user_model()


class StudentDashboard(TemplateView):
    template_name = 'student/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"DA | {self.request.user}"
        context['navbar'] = "student-dashboard"
        context['user'] = User.objects.get(id=self.request.user.id)
        return context


class CourseList(ListView):
    paginate_by = 8
    model = Course
    template_name = 'student/explore.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Courses | {self.request.user.first_name}"
        context['navbar'] = "student-explore"
        return context


def course_subscribe(request):
    c_id = request.GET.get('id')
    c = Course.objects.get(id=c_id)
    cr = CourseRegistration.objects.filter(student=request.user)
    data = {}
    if cr.filter(course_id=c_id).exists():
        data['message'] = "Already Subscribed to Course"
        data['color'] = "alert-danger"

    else:
        CourseRegistration.objects.create(
            student=request.user,
            course=c,
            subscribed=True
        )
        data['message'] = "Successfully Subscribed to course. Go to you Course Section"
        data['color'] = "alert-success"
    return JsonResponse(data)


class SubscribedCourses(ListView):
    template_name = 'student/my-courses.html'
    paginate_by = 8

    def get_queryset(self):
        return CourseRegistration.objects.filter(student=self.request.user, subscribed=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"My Courses | {self.request.user.first_name}"
        context['navbar'] = "student-courses"
        return context


def unsubscribe(request):
    if request.method == 'GET':
        idx = request.GET.get('idx')
        crd = CourseRegistration.objects.get(id=idx)
        crd.delete()
        return JsonResponse({"data": idx})


class SearchCourse(ListView):
    paginate_by = 8
    model = Course
    template_name = 'student/explore.html'

    def get_queryset(self):
        return Course.objects.filter(course_name__icontains=self.request.GET.get('query'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f"Courses | {self.request.user.first_name}"
        context['navbar'] = "student-explore"
        return context

student/templates/student/course-details-page.html
<div class="modal top fade" id="course-detail-page" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
     data-mdb-backdrop="static" data-mdb-keyboard="true">
    <div class="modal-dialog modal-dialog-scrollable  modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header" style="padding-left: 1rem; padding-bottom: 0">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
            </div>
            <span class="modal-title" id="description" style="padding-left: 1rem;"></span>
            <hr class="mt-0 mb-0">
            <div class="modal-body" id="content">


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-block btn-sm btn-dark" data-mdb-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>

student/templates/student/explore.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="alert py-1 mt-2 text-center" id="notify" role="alert" style="display: none">

        </div>
        <form action="{% url 'student:search' %}" class="mb-2 mt-4">
            <input id="query" name="query" type="text" class="form-control" placeholder="Search Courses">
        </form>
        <div class="row mt-3 mb-4 mx-1">
            <div class="card shadow-custom">
                <h5 class="text-muted text-center pb-2 pt-2 border-2 border-bottom">Explore Latest Courses</h5>
                <div class="card" id="courses">
                    {% for course in course_list %}
                        <div class="card-body" id="card-body">
                            <h5 class="card-title mb-0" id="title">{{ course.course_name|title }}</h5>
                            <hr class="my-1">
                            <small>{% for content in course.content_set.all %}
                                <li>{{ content.topic }}</li>
                            {% endfor %}
                            </small>
                            <p class="card-text mt-2">
                                {{ course.content_set.content }}
                            </p>
                            <a href="{% url 'teacher:confirm-order' course.id %}" data-course_id="{{ course.id }}"
                               id="subscribe"
                               class="btn btn-sm btn-success">₹ {{ course.price }}</a>
                        </div>
                        <hr>
                        {% empty %}
                        <div class="card-body">
                            <h5 class="card-title mb-0">No Courses Found</h5>
                        </div>
                    {% endfor %}
                </div>

                {% if course_list %}
                    <div class='pagination justify-content-center pb-2' id="pg">
                        {% if page_obj.has_previous %}
                            <a href='?page={{ page_obj.previous_page_number }}'>Previous </a>
                        {% endif %}
                        <span class='mx-2'>
                          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>
                        {% if page_obj.has_next %}
                            <a href='?page={{ page_obj.next_page_number }}'>Next</a>
                        {% endif %}
                    </div>

                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}

{% block app-js %}
    <script>

    </script>
{% endblock %}

student/templates/student/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row d-flex justify-content-center align-items-center mt-4 mx-1" style="min-height: 60vh">
            <div class="card shadow-custom">
                <h4 class="text-center p-2">Welcome To Digi Academy
                </h4>
                <hr>
                <div class="row text-center mt-4 mb-4">
                    <div class="col-lg-3">
                        <a href="{% url 'student:student-dashboard' %}" class="btn btn-sm btn-success mb-2 w-100">Dashboard</a>
                    </div>
                    <div class="col-lg-3">
                        <a href="{% url 'student:my-courses' %}" class="btn btn-sm btn-success mb-2 w-100">Courses</a>
                    </div>
                    <div class="col-lg-3">
                        <a href="{% url 'student:student-explore' %}"
                           class="btn btn-sm btn-success mb-2 w-100">Explore</a>
                    </div>
                    <div class="col-lg-3">
                        <a href="{% url 'user:logout' %}" class="btn btn-sm btn-danger mb-2 w-100">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}

student/templates/student/my-courses.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row my-4 mx-1">
            <div class="card shadow-custom p-2">
                <h5 class="text-center">Subscribed Courses</h5>
                <hr class="mt-0">
                <div class="table-responsive">
                    <table class="table table-bordered border-black table-sm table-striped table-hover table-light border-light"
                           id="sc">
                        <thead class="table-dark">
                        <tr class="">
                            <th scope="col">#</th>
                            <th scope="col">Instructor</th>
                            <th scope="col">Course</th>
                            <th scope="col">Topics</th>
                        </tr>
                        </thead>
                        <tbody id="tb">
                        {% for object in object_list %}
                            <tr id="row-{{ object.id }}">
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ object.course.instructor.first_name|title }}</td>
                                <td>{{ object.course.course_name|title }}</td>
                                <td>{% for foo in object.course.content_set.all %}
                                    <li><a href="#" id="view-course"
                                           data-mdb-toggle="modal"
                                           data-mdb-target="#course-detail-page"
                                           data-title="{{ object.course.course_name|title }}"
                                           data-description="{{ foo.topic|title }}"
                                           data-content="{{ foo.content|capfirst }}">{{ foo.topic }}</a>
                                    </li>
                                {% endfor %}
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="7" class="text-center">No Courses Subscribed</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% include 'student/course-details-page.html' %}
                </div>
                {% if object_list %}
                    <div class='pagination justify-content-center pb-2' id="pg">
                        {% if page_obj.has_previous %}
                            <a href='?page={{ page_obj.previous_page_number }}'>Previous </a>
                        {% endif %}
                        <span class='mx-2'>
                      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                        {% if page_obj.has_next %}
                            <a href='?page={{ page_obj.next_page_number }}'>Next</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}
{% block app-js %}
    <script>
        $('[id="view-course"]').on('click', function () {
            $("#exampleModalLabel").text($(this).data('title'));
            $("#description").text($(this).data('description'));
            $("#content").text($(this).data('content'));
        });
    </script>
{% endblock %}

student/templates/student/order-confirm.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row d-flex justify-content-center align-items-center mt-4 mx-1" style="min-height: 60vh">
            <div class="card shadow-custom">
                <h4 class="text-center pt-2">Confirm Your Order</h4>
                <hr class="mt-1">
                <div class="p-5">
                    <h3>{{ course.course_name }}</h3>
                    <h3>₹ {{ course.price }}</h3>
                    <form action="#" method="post">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-sm btn-dark" value="proceed">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}

student/templates/student/pay.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row d-flex justify-content-center align-items-center mt-4 mx-1" style="min-height: 60vh">
            <div class="card shadow-custom">
                <h4 class="text-center pt-2">Proceed to pay</h4>
                <hr class="mt-1">
                <div class="p-5 text-center">
                    {{ form.render }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}

student/templates/student/payment-failed.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row d-flex justify-content-center align-items-center mt-4 mx-1" style="min-height: 60vh">
            <div class="card shadow-custom">
                <h4 class="text-center my-2 text-danger">Payment Failed</h4>
                <hr class="my-1">
                <a href="{% url "student:student-explore" %}" class="btn btn-sm btn-dark my-3">Explore Again</a>
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}

student/templates/student/payment-success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block app-css %}
    <style>
        .shadow-custom {
            box-shadow: 0 2px 20px 0 rgba(0, 0, 0, .25), 0 3px 10px 5px rgba(0, 0, 0, 0.05) !important;
        }
    </style>
{% endblock %}
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
{% block content %}
    <div class="container" style="min-height: 100vh">
        {% include 'components/alert.html' %}
        <div class="row d-flex justify-content-center align-items-center mt-4 mx-1" style="min-height: 60vh">
            <div class="card shadow-custom">
                <h4 class="text-center my-2 text-success">Payment Success</h4>
                <hr>
                <a href="{% url 'student:my-courses' %}" class="btn btn-sm btn-success my-3">got to your courses</a>
            </div>
        </div>
    </div>
{% endblock %}
{% block footbar %}
    {% include 'components/footer.html' %}
{% endblock %}