config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('student/', include('student.urls', namespace='student')),
    path('teacher/', include('teacher.urls', namespace='teacher')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Digi Academy Admin'
admin.site.site_title = 'Digi Academy Admin'
admin.site.index_title = 'Digi Academy Admin'

student/urls.py
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path('', views.StudentDashboard.as_view(), name='student-dashboard'),
    path('explore/', views.CourseList.as_view(), name='student-explore'),
    path('subscribe/', views.course_subscribe, name='subscribe'),
    path('my-courses/', views.SubscribedCourses.as_view(), name='my-courses'),
    path('unsubscribe/', views.unsubscribe, name='un-subscribe'),
    path('search/', views.SearchCourse.as_view(), name='search'),
]

teacher/urls.py
from django.urls import path

from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.TeacherDashboard.as_view(), name='teachers-dashboard'),
    path('courses/', views.CoursesList.as_view(), name='teachers-courses'),
    path('add-courses/', views.CourseCreate.as_view(), name='create-courses'),
    path('<int:pk>/delete/', views.delete_content, name='delete-content'),
    path('<int:pk>/delete/courses/', views.delete_course, name='delete-course'),
    path('<int:pk>/edit/', views.edit_content, name='edit-content'),
    path('<int:pk>/add-topic/', views.add_topic, name='add_topic'),
    path('student-list/', views.StudentList.as_view(), name='student-list'),
    path('confirm-order/<int:pk>/', views.confirm_order, name='confirm-order'),
    path('process-payment/', views.process_payment, name='process_payment'),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.welcome_page, name='welcome'),
    path('student-login/', views.StudentLoginView.as_view(), name='student-login'),
    path('student-register/', views.StudentRegisterView.as_view(), name='student-register'),
    path('verify-otp/<email>', views.VerifyOtp.as_view(), name='verify-otp'),
    path('teacher-login/', views.TeacherLoginView.as_view(), name='teacher-login'),
    path('teacher-register/', views.TeacherRegisterView.as_view(), name='teacher-register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

templates/components/alert.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} p-2 mt-4 text-center" id="message" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/components/footer.html
<footer class=" text-center text-white" style="background-color:#262626;">

    <div class="text-center p-3" style="background-color: rgb(38,38,38)">
        © {% now 'Y' %} Copyright:
        <a class="text-white" href="#"><i class="fa fa-asterisk fa-1x ps-1"></i></a>
    </div>
</footer>

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <i class="fa fa-asterisk fa-2x ps-1"></i>
        </a>
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        {% if request.user.is_student %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if navbar == 'student-dashboard' %}active{% endif %}"
                           href="{% url 'student:student-dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if navbar == 'student-courses' %}active{% endif %}"
                           href="{% url 'student:my-courses' %}">My-Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if navbar == 'student-explore' %}active{% endif %}"
                           href="{% url 'student:student-explore' %}">Explore</a>
                    </li>
                </ul>
                <ul class="navbar-nav d-flex flex-row ms-auto me-3">
                    <li class="nav-item me-3 me-lg-0 dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown1" role="button"
                           data-mdb-toggle="dropdown"
                           aria-expanded="false">
                            <i class="fas fa-user fa-1x"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown1">
                            <li><a class="dropdown-item disabled" href="#">{{ request.user }}</a></li>
                            <li><a class="dropdown-item" href="{% url 'user:logout' %}">Sign out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        {% endif %}
        {% if request.user.is_authenticated and request.user.is_teacher %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if navbar == 'teacher-dashboard' %}active{% endif %}"
                           href="{% url 'teacher:teachers-dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if navbar == 'teacher-courses' %}active{% endif %}"
                           href="{% url 'teacher:teachers-courses' %}">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if navbar == 'teacher-students' %}active{% endif %}"
                           href="{% url 'teacher:student-list' %}">Students</a>
                    </li>
                </ul>
                <ul class="navbar-nav d-flex flex-row ms-auto me-3">
                    <li class="nav-item me-3 me-lg-0 dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown1" role="button"
                           data-mdb-toggle="dropdown"
                           aria-expanded="false">
                            <i class="fas fa-user fa-1x"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown1">
                            <li><a class="dropdown-item disabled" href="#">{{ request.user }}</a></li>
                            <li><a class="dropdown-item" href="{% url 'user:logout' %}">Sign out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        {% endif %}
    </div>
</nav>